### ISSUE TITLE
Week of 9/21

### ISSUE THREAD

**Issue by kevkevin999** [Husky-Coding-Project/chow-down#48]
### Tasks as assigned during meeting:
**Steven, Kevin X., Minyoung**: Fix Size of Add Review Box (see comment below for details)
**Kevin W**: Add comments to code
**Kevin W**: Fix ReadMe in GitHub
**Kevin X**: add fake reviews in MOCK_DATA.json, fix map position, 
**Minyoung**: Custom Review Boxes --> use .map or for-each loop to iterate through each element in reviews, display on BusinessPage.js

### Tier 2 / Lower Priority Tasks (check off if you're working on it):
- [x] Allow searching for special characters (try searching _Pho Shizzle_ or _Cafe_) 
- [x] Allow search bar to accept cuisine
- [ ] IN PROGRESS: If no search results pop up, display alert/alternative screen ("oops, no restaurants match your search criteria")
- [ ] find links to photos for restaurants and add to MOCK_DATA.json
- [ ] markers on map (if somebody has infinite time...)
- [ ] Fix 'Add Review' Button on BusinessPage.js (make sure it's centered - don't use numeric margin amounts as that isn't compatible with all devices)

If you have other tasks you wish to see implemented, feel free to add it to this list!

**Comment by kevkevin999** [comment]
Approach: Add max length for reviews - like Twitter
See if you can get automatic next line when typing.
